### ISSUE TITLE
questions about framework used in your project

### ISSUE THREAD

**Issue by CrazyPopLin** [andybarry/flight#5]
Hi I am super new to LCM an just went through homepage about the introduces and tutorials. But it seems no detail tutorials. I have experiences in ROS but want to use some small framework to develop our project. Algorithm processed in onboard computer( arm ubuntu) with copter to avoid obstacles.

Can I ask questions about framework which integrated in your whole project. Is that LCM connected every module together like several ROS nodes with pub/sub mechanism. It seems that LCM use broadly in multi-mechines communication not computer threads.

I try to use the [flight controller API (drone-python)](http://python.dronekit.io/) to communicate between onboard computer and Pixhawk which uses APM copter firmware. Because that's more stable and functional API. And stereo-camera with opencv to acquire obstacle data in c++, like depth map, etc. I wan to use LCM sub/pub message mechanism to wrap this two modules. maybe more modules in the future. Is that possible?

Please correct my misunderstanding and give me some suggestions. Thanks for your help.

**Comment by andybarry** [comment]
Hi,

Yes, I saw your message on the LCM list.  LCM is a message passing system,
similar to ROS pub/sub, but with some small differences.  There is no
master in LCM and traffic is sent via UDP multicast.  There are some good
tutorials here: https://lcm-proj.github.io/tutorial_general.html
